[workspace]
authors = ['philly12399 <philly12399@gmail.com>']
resolver = "2"
members = [
    "static-point-filter",
    "range-point-filter",
    "generic-point-filter",
    "point-filter-tool",
    "filter-expr",
]
